### ISSUE TITLE
Document configuring with `pyproject.toml`

### ISSUE THREAD

**Issue by bgilbert** [pypa/wheel#582]
[This page](https://wheel.readthedocs.io/en/stable/user_guide.html#building-wheels) notes that wheel reads settings from `setup.cfg`, but wheel's documentation is silent on whether `pyproject.toml` can be used instead.  It appears that it can:

```toml
[tool.distutils.bdist_wheel]
py-limited-api = "cp311"
```

Please consider explicitly documenting this.
